server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/jeonmoo/e-commerce-msa-config.git
          default-label: master
