server:
  port: 8080

spring:
  application:
    name: order
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes: []

    config:
      server:
        git:
          uri: https://github.com/jeonmoo/e-commerce-msa-config.git

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info
